import React, { useState, useCallback } from 'react';
import { AppStep, AIProvider, INITIAL_DATA, WizardData } from './types';
import { generateMasterPrompt } from './services/aiService';
import { BasicsStep, TechStackStep, FeaturesStep, ConstraintsStep, StepErrors } from './components/WizardSteps';
import { Button } from './components/common';

const STEP_LABELS = ["Basics", "Tech Stack", "Features", "Constraints", "Review", "Result"];

const PROVIDER_CONFIG: Record<AIProvider, { label: string; color: string; dot: string }> = {
  gemini: { label: 'Gemini', color: 'text-blue-400', dot: 'bg-blue-400' },
  claude: { label: 'Claude', color: 'text-orange-400', dot: 'bg-orange-400' },
  openai: { label: 'OpenAI', color: 'text-green-400', dot: 'bg-green-400' }
};

const PROVIDERS = Object.keys(PROVIDER_CONFIG) as AIProvider[];

function validateStep(step: AppStep, data: WizardData): StepErrors {
  const errors: StepErrors = {};
  if (step === AppStep.BASICS) {
    if (!data.projectName.trim()) errors.projectName = 'Project name is required.';
    if (!data.projectDescription.trim()) errors.projectDescription = 'Project description is required.';
  }
  if (step === AppStep.TECH_STACK) {
    if (!data.techStack.frontend.trim()) errors.frontend = 'Frontend technology is required.';
  }
  if (step === AppStep.FEATURES) {
    if (data.coreFeatures.length === 0) errors.coreFeatures = 'Add at least one core feature.';
  }
  return errors;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slugify(name: string) {
  return name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') || 'project';
}

function App() {
  const [currentStep, setCurrentStep] = useState<AppStep>(AppStep.BASICS);
  const [data, setData] = useState<WizardData>(INITIAL_DATA);
  const [provider, setProvider] = useState<AIProvider>('gemini');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState('');
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [editablePrompt, setEditablePrompt] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [stepErrors, setStepErrors] = useState<StepErrors>({});
  const [copied, setCopied] = useState(false);

  const updateData = useCallback((updates: Partial<WizardData>) => {
    setData(prev => ({ ...prev, ...updates }));
    setStepErrors({});
  }, []);

  const runGenerate = async () => {
    setGenerateError('');
    setIsGenerating(true);
    try {
      const result = await generateMasterPrompt(data, provider);
      setGeneratedPrompt(result);
      setEditablePrompt(result);
      setCurrentStep(AppStep.RESULT);
    } catch (err: any) {
      setGenerateError(err.message || 'Generation failed. Check that the server is running.');
    } finally {
      setIsGenerating(false);
    }
  };

  const nextStep = async () => {
    if (currentStep < AppStep.CONSTRAINTS) {
      const errors = validateStep(currentStep, data);
      if (Object.keys(errors).length > 0) {
        setStepErrors(errors);
        return;
      }
    }
    if (currentStep === AppStep.CONSTRAINTS) {
      setCurrentStep(AppStep.REVIEW);
    } else if (currentStep === AppStep.REVIEW) {
      await runGenerate();
    } else {
      setStepErrors({});
      setCurrentStep(prev => prev + 1);
    }
  };

  const prevStep = () => {
    if (currentStep > 0 && currentStep !== AppStep.RESULT) {
      setStepErrors({});
      setCurrentStep(prev => prev - 1);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(editablePrompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const slug = slugify(data.projectName);
    const content = `# ${data.projectName} - Master Prompt\n\n> Generated by AppPrompt Architect\n\n---\n\n${editablePrompt}`;
    downloadFile(content, `${slug}-master-prompt.md`, 'text/markdown');
  };

  const handleDownloadJSON = () => {
    const slug = slugify(data.projectName);
    const payload = { metadata: data, provider, masterPrompt: editablePrompt };
    downloadFile(JSON.stringify(payload, null, 2), `${slug}-spec.json`, 'application/json');
  };

  const handleRegenerate = async () => {
    setCurrentStep(AppStep.REVIEW);
    await runGenerate();
  };

  const handleReset = () => {
    setData(INITIAL_DATA);
    setGeneratedPrompt('');
    setEditablePrompt('');
    setGenerateError('');
    setStepErrors({});
    setIsEditing(false);
    setCurrentStep(AppStep.BASICS);
  };

  const renderContent = () => {
    const stepProps = { data, updateData, errors: stepErrors, provider };

    switch (currentStep) {
      case AppStep.BASICS: return <BasicsStep {...stepProps} />;
      case AppStep.TECH_STACK: return <TechStackStep {...stepProps} />;
      case AppStep.FEATURES: return <FeaturesStep {...stepProps} />;
      case AppStep.CONSTRAINTS: return <ConstraintsStep {...stepProps} />;

      case AppStep.REVIEW:
        return (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div>
              <h2 className="text-2xl font-bold text-white mb-2">Review Summary</h2>
              <p className="text-slate-400">Check everything before generating your Master Prompt.</p>
            </div>
            {generateError && (
              <div className="bg-red-900/20 border border-red-500/40 text-red-300 text-sm rounded-lg px-4 py-3">{generateError}</div>
            )}
            <div className="bg-dark-900 rounded-lg p-6 border border-dark-800 space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div><span className="text-slate-500">Name:</span> <span className="text-slate-200">{data.projectName}</span></div>
                <div><span className="text-slate-500">Type:</span> <span className="text-slate-200">{data.projectType}</span></div>
                <div className="col-span-2"><span className="text-slate-500">Audience:</span> <span className="text-slate-200">{data.targetAudience || '-'}</span></div>
              </div>
              <div className="border-t border-dark-800 pt-4">
                <p className="text-slate-400 text-sm">{data.projectDescription}</p>
              </div>
              <div className="border-t border-dark-800 pt-4">
                <h4 className="text-primary-400 text-xs font-semibold uppercase tracking-wider mb-2">Stack</h4>
                <p className="text-slate-300 text-sm">{Object.values(data.techStack).filter(Boolean).map(v => Array.isArray(v) ? v.join(', ') : v).join(' - ')}</p>
              </div>
              <div className="border-t border-dark-800 pt-4">
                <h4 className="text-primary-400 text-xs font-semibold uppercase tracking-wider mb-2">Features ({data.coreFeatures.length})</h4>
                <ul className="list-disc list-inside text-slate-300 text-sm space-y-1">{data.coreFeatures.map((f, i) => <li key={i}>{f}</li>)}</ul>
              </div>
              {(data.securityReqs || data.securitySpecifics) && (
                <div className="border-t border-dark-800 pt-4">
                  <h4 className="text-primary-400 text-xs font-semibold uppercase tracking-wider mb-2">Security</h4>
                  <p className="text-slate-300 text-sm">{data.securityReqs || '-'}</p>
                </div>
              )}
              <div className="border-t border-dark-800 pt-4 flex items-center gap-2 text-sm">
                <span className="text-slate-500">AI Provider:</span>
                <span className={`font-medium ${PROVIDER_CONFIG[provider].color}`}>{PROVIDER_CONFIG[provider].label}</span>
              </div>
            </div>
          </div>
        );

      case AppStep.RESULT:
        return (
          <div className="space-y-5 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <h2 className="text-2xl font-bold text-white">Your Master Prompt</h2>
                <p className="text-slate-500 text-sm mt-0.5">Generated with {PROVIDER_CONFIG[provider].label} - {editablePrompt.length.toLocaleString()} chars</p>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button variant="secondary" onClick={handleCopy} className="text-sm py-2 px-4">{copied ? 'Copied' : 'Copy'}</Button>
                <Button variant="secondary" onClick={handleDownloadMarkdown} className="text-sm py-2 px-4">.md</Button>
                <Button variant="secondary" onClick={handleDownloadJSON} className="text-sm py-2 px-4">.json</Button>
                <Button variant="secondary" onClick={() => setIsEditing(e => !e)} className="text-sm py-2 px-4">{isEditing ? 'Preview' : 'Edit'}</Button>
              </div>
            </div>
            {isEditing ? (
              <textarea value={editablePrompt} onChange={(e) => setEditablePrompt(e.target.value)}
                className="w-full bg-dark-900 border border-dark-800 rounded-lg p-6 font-mono text-sm leading-relaxed text-slate-300 focus:outline-none focus:ring-2 focus:ring-primary-500 min-h-[50vh]" />
            ) : (
              <div className="bg-dark-900 rounded-lg p-6 border border-dark-800 font-mono text-sm leading-relaxed whitespace-pre-wrap text-slate-300 overflow-x-auto max-h-[60vh] overflow-y-auto">{editablePrompt}</div>
            )}
            <div className="flex gap-3">
              <Button variant="ghost" onClick={handleRegenerate} disabled={isGenerating} className="text-sm">
                {isGenerating ? 'Regenerating...' : 'Regenerate'}
              </Button>
            </div>
          </div>
        );

      default: return null;
    }
  };

  const canGoBack = currentStep > 0 && currentStep !== AppStep.RESULT;
  const isReviewStep = currentStep === AppStep.REVIEW;
  const isResultStep = currentStep === AppStep.RESULT;

  return (
    <div className="min-h-screen bg-dark-950 flex">
      <div className="w-64 border-r border-dark-800 bg-dark-900/50 p-8 hidden md:flex flex-col">
        <div className="mb-10">
          <div className="flex items-center gap-3 text-primary-500 mb-2">
            <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
            </svg>
            <span className="font-bold text-xl tracking-tight text-slate-100">PromptArchitect</span>
          </div>
          <p className="text-xs text-slate-500">AI-Assisted Spec Generator</p>
        </div>
        <div className="space-y-1 flex-1">
          {STEP_LABELS.map((label, idx) => {
            const isActive = idx === currentStep;
            const isPast = idx < currentStep;
            return (
              <div key={label} className={`flex items-center gap-3 px-3 py-2 rounded-md transition-colors ${isActive ? 'bg-primary-900/20 text-primary-400' : isPast ? 'text-slate-400' : 'text-slate-600'}`}>
                <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-medium border shrink-0 ${isActive ? 'border-primary-500 text-primary-500' : isPast ? 'border-slate-600 bg-slate-800/50 text-slate-500' : 'border-slate-800 text-slate-700'}`}>
                  {isPast ? 'v' : idx + 1}
                </div>
                <span className="text-sm font-medium">{label}</span>
              </div>
            );
          })}
        </div>
        <div className="mt-8 pt-6 border-t border-dark-800">
          <p className="text-xs text-slate-500 font-medium uppercase tracking-wider mb-3">AI Provider</p>
          <div className="flex flex-col gap-2">
            {(Object.keys(PROVIDER_CONFIG) as AIProvider[]).map(p => {
              const cfg = PROVIDER_CONFIG[p];
              const isSelected = provider === p;
              return (
                <button key={p} onClick={() => setProvider(p)}
                  className={`flex items-center gap-2.5 px-3 py-2.5 rounded-lg border text-sm font-medium transition-all ${isSelected ? 'bg-dark-800 border-dark-600 text-slate-200' : 'bg-transparent border-dark-800 text-slate-500 hover:border-dark-700 hover:text-slate-400'}`}>
                  <span className={`w-2 h-2 rounded-full ${cfg.dot} ${!isSelected && 'opacity-40'}`} />
                  {cfg.label}
                  {isSelected && <span className="ml-auto text-xs text-slate-500">active</span>}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <div className="flex-1 flex flex-col h-screen overflow-hidden">
        <header className="h-14 border-b border-dark-800 flex items-center px-5 justify-between md:hidden shrink-0">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-primary-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
            </svg>
            <span className="font-bold text-slate-200 text-sm">PromptArchitect</span>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={() => setProvider(p => PROVIDERS[(PROVIDERS.indexOf(p) + 1) % PROVIDERS.length])}
              className={`text-xs font-medium px-2 py-1 rounded border border-dark-700 bg-dark-800 ${PROVIDER_CONFIG[provider].color}`}>
              {PROVIDER_CONFIG[provider].label}
            </button>
            <span className="text-xs text-slate-500">{currentStep + 1}/{STEP_LABELS.length}</span>
          </div>
        </header>
        <div className="flex items-center gap-1.5 px-5 py-2 border-b border-dark-800/50 md:hidden shrink-0">
          {STEP_LABELS.map((label, idx) => (
            <div key={label} className={`h-1 rounded-full flex-1 transition-all ${idx === currentStep ? 'bg-primary-500' : idx < currentStep ? 'bg-slate-600' : 'bg-dark-800'}`} />
          ))}
        </div>
        <div className="flex items-center px-5 py-1.5 md:hidden shrink-0">
          <span className="text-xs font-medium text-slate-400">{STEP_LABELS[currentStep]}</span>
        </div>
        <main className="flex-1 overflow-y-auto p-5 md:p-12">
          <div className="max-w-3xl mx-auto">{renderContent()}</div>
        </main>
        <footer className="shrink-0 border-t border-dark-800 bg-dark-900/30 px-5 md:px-12 py-4 flex items-center justify-between gap-3">
          <Button variant="ghost" onClick={prevStep} disabled={!canGoBack}>Back</Button>
          {!isResultStep && (
            <Button onClick={nextStep} disabled={isGenerating} className={isGenerating ? 'animate-pulse' : ''}>
              {isReviewStep ? (isGenerating ? 'Generating...' : 'Generate Master Prompt') : 'Continue'}
            </Button>
          )}
          {isResultStep && <Button variant="secondary" onClick={handleReset}>Start New Project</Button>}
        </footer>
      </div>
    </div>
  );
}

export default App;
